POST http://localhost:3000/send
Content-Type: application/json

{
    "name":"Señor cosquillas",
    "position":"CIO",
    "salary":"5000.5",
    "picture":"",
    "email":"email@email.com",
    "phone":"84752940-4"
}
###

GET http://localhost:3000/

###
DELETE http://localhost:3000/delete/6346dee76cf97990c6dc979b

###
PUT http://localhost:3000/update/633f50f6bda57c31f35420d4
Content-Type: application/json

{
    "name":"El rompe catres 3000*2",
    "position":"CIO",
    "salary":"5000.5",
    "picture":"",
    "email":"email@email.com",
    "phone":"84752940-4"
}